service: blog
image: ermeson/blog

ssh:
  user: root
  keys: ['~/.ssh/hetzner']

servers:
  web:
    - blog.zapsecreto.com.br

proxy:
  ssl: true
  host: blog.zapsecreto.com.br
  app_port: 80
  healthcheck:
    path: /

registry:
  server: localhost:5555

builder:
  arch: amd64

env:
  clear:
    APP_ENV: production
