service: blog
image: ermeson/blog

ssh:
  user: root
  keys: ['~/.ssh/hetzner']

servers:
  web:
    - ermeson.is-a.dev

proxy:
  ssl: true
  host: ermeson.is-a.dev
  app_port: 80
  healthcheck:
    path: /

registry:
  server: localhost:5555

builder:
  arch: amd64

env:
  clear:
    APP_ENV: production
