service: blog-api
image: ermeson/blog-api

ssh:
    user: root
    keys: ["~/.ssh/hetzner"]

servers:
    web:
        - blog.zapsecreto.com.br

readiness_delay: 60
proxy:
    host: blog.zapsecreto.com.br
    app_port: 80
    path_prefix: /api
    healthcheck:
        path: /api/up
        interval: 30
        timeout: 5

labels:
    traefik.http.routers.blog-api.tls: "true"
    traefik.http.routers.blog-api.tls.certresolver: "letsencrypt"

registry:
    server: localhost:5555

builder:
    arch: amd64

env:
    clear:
        CADDY_GLOBAL_OPTIONS: "admin off"
        DB_HOST: psql
        DB_NAME: blog
        DB_USER: postgres
    secret:
        - DB_PASSWORD

accessories:
    psql:
        image: postgres:16-alpine
        host: blog.zapsecreto.com.br
        port: 5432
        env:
            clear:
                POSTGRES_USER: postgres
                DB_NAME: blog
            secret:
                - POSTGRES_PASSWORD
        directories:
            - data:/var/lib/postgresql/data
